### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by TechGeeksIO** [Lepkem/traefik-plugin-response-code-override#10]
Is this plugin still working with traefik latest version?

I try to redirect 403 to 444, but unfortunately I still get the forbidden message.

My dynamic conf
```
http:
  middlewares:
    http-error-code:
      plugin:
        plugin-response-code-override:
          RemoveBody: false
          HeadersToRemove:
            - "Referrer-Policy"
            - "Alt-Svc"
            - "X-Be"
            - "H1"
          Overrides:
            '403': 444
```

My static conf
```
pilot:
    token: "XXX"
experimental:
  plugins:
    plugin-response-code-override:
      moduleName: github.com/Lepkem/traefik-plugin-response-code-override
      version: v0.0.3
```

and in my composer file i added the following line:
`- "traefik.http.routers.portainer.middlewares=protected-ipwhitelist@file, http-error-code@file"`

Any ideas? Thanks!
